# yaml file to configure readthedocs build
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
python:
  install:
    - requirements: docs/source/requirements.txt
sphinx:
  configuration: docs/source/conf.py
